# Generated by Django 3.2.13 on 2022-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_point',
            field=models.IntegerField(default=0),
        ),
    ]
